######## Given peptide sequence get start and end position

SELECT peptide_start, protein_id FROM peptide WHERE peptide_sequence ='MMKFKPNQ';
SELECT peptide_end, protein_id FROM peptide WHERE peptide_sequence ='MMKFKPNQ';

######## Given peptide sequence get pre and post context

SELECT peptide_pre_context, protein_id FROM peptide WHERE peptide_sequence ='MMKFKPNQ';
SELECT peptide_pre_context, protein_id FROM peptide WHERE peptide_sequence ='MMKFKPNQ';



###### Give the protein get the peptides
SELECT * FROM peptide WHERE protein_id = (SELECT protein_id FROM protein WHERE TRIM(protein_sequence) = 'MVIMSEFSADPAGQGQGQQKPLRVGFYDIERTLGKGNFAVVKLARHRVTKTQVAIKIIDKTRLDSSNLEKIYREVQLMKLLNHPHIIKLYQVMETKDMLYIVTEFAKNGEMFDYLTSNGHLSENEARKKFWQILSAVEYCHDHHIVHRDLKTENLLLDGNMDIKLADFGFGNFYKSGEPLSTWCGSPPYAAPEVFEGKEYEGPQLDIWSLGVVLYVLVCGSLPFDGPNLPTLRQRVLEGRFRIPFFMSQDCESLIRRMLVVDPARRITIAQIRQHRWMRAEPCLPGPACPAFSAHSYTSNLGDYDEQALGIMQTLGVDRQRTVESLQNSSYNHFAAIYYLLLERLKEYRNAQCARPGPARQPRPRSSDLSGLEVPQEGLSTDPFRPALLCPQPQTLVQSVLQAEMDCELQSSLQWPLFFPVDASCSGVFRPRPVSPSSLLDTAISEEARQGPGLEEEQDTQESLPSSTGRRHTLAEVSTRLSPLTAPCIVVSPSTTASPAEGTSSDSCLTFSASKSPAGLSGTPATQGLLGACSPVRLASPFLGSQSATPVLQAQGGLGGAVLLPVSFQEGRRASDTSLTQGLKAFRQQLRKTTRTKGFLGLNKIKGLARQVCQVPASRASRGGLSPFHAPAQSPGLHGGAAGSREGWSLLEEVLEQQRLLQLQHHPAAAPGCSQAPQPAPAPFVIAPCDGPGAAPLPSTLLTSGLPLLPPPLLQTGASPVASAAQLLDTHLHIGTGPTALPAVPPPRLARLAPGCEPLGLLQGDCEMEDLMPCSLGTFVLVQ');

SELECT peptide_sequence FROM peptide WHERE protein_id = (SELECT protein_id FROM protein WHERE TRIM(protein_sequence) = 'MVIMSEFSADPAGQGQGQQKPLRVGFYDIERTLGKGNFAVVKLARHRVTKTQVAIKIIDKTRLDSSNLEKIYREVQLMKLLNHPHIIKLYQVMETKDMLYIVTEFAKNGEMFDYLTSNGHLSENEARKKFWQILSAVEYCHDHHIVHRDLKTENLLLDGNMDIKLADFGFGNFYKSGEPLSTWCGSPPYAAPEVFEGKEYEGPQLDIWSLGVVLYVLVCGSLPFDGPNLPTLRQRVLEGRFRIPFFMSQDCESLIRRMLVVDPARRITIAQIRQHRWMRAEPCLPGPACPAFSAHSYTSNLGDYDEQALGIMQTLGVDRQRTVESLQNSSYNHFAAIYYLLLERLKEYRNAQCARPGPARQPRPRSSDLSGLEVPQEGLSTDPFRPALLCPQPQTLVQSVLQAEMDCELQSSLQWPLFFPVDASCSGVFRPRPVSPSSLLDTAISEEARQGPGLEEEQDTQESLPSSTGRRHTLAEVSTRLSPLTAPCIVVSPSTTASPAEGTSSDSCLTFSASKSPAGLSGTPATQGLLGACSPVRLASPFLGSQSATPVLQAQGGLGGAVLLPVSFQEGRRASDTSLTQGLKAFRQQLRKTTRTKGFLGLNKIKGLARQVCQVPASRASRGGLSPFHAPAQSPGLHGGAAGSREGWSLLEEVLEQQRLLQLQHHPAAAPGCSQAPQPAPAPFVIAPCDGPGAAPLPSTLLTSGLPLLPPPLLQTGASPVASAAQLLDTHLHIGTGPTALPAVPPPRLARLAPGCEPLGLLQGDCEMEDLMPCSLGTFVLVQ');

###### Given the peptide get the proteins
SELECT * FROM peptide WHERE TRIM(peptide_sequence) = 'MMKFKPNQ';

# Note: Multiple Proteins with same sequence
select protein_id, protein_info, TRIM(protein_sequence) FROM protein 
WHERE protein_id IN (SELECT protein_id FROM peptide WHERE TRIM(peptide_sequence) = 'MMKFKPNQ');

###### GET BINDING AFFINITY BY PEPTIDE 
select * FROM predict WHERE TRIM(peptide_sequence) = 'MMKFKPNQ';

###### THE BEST ALLELE FOR PEPTIDE OF INTEREST
select peptide_sequence, best_msi_allele, min(msi) FROM predict 
	WHERE TRIM(peptide_sequence) = 'MMKFKPNQ' 
	GROUP BY peptide_sequence, best_msi_allele 
	ORDER BY min(msi) 
	ASC LIMIT 1;
